const express=require("express")
const app=express()
const cors=require("cors")
const  compression=require('compression')
const helmet = require("helmet")
const DB=require("./database/index")
require("dotenv").config();
DB()
app.use(cors())
app.use(express.json())
app.use(compression())
app.use(helmet())
app.use('/api/post',require("./routes/POST"))
app.use('/api/get',require("./routes/GET"))
app.listen(5000,()=>{
    console.log("server is up and running")
})